### ISSUE TITLE
Back end route: /multi_store_customers

### ISSUE THREAD

**Issue by MystikHub** [MystikHub/sweng-12#13]
This route should follow the format we discussed:

example: /multi_store_customers?store=001
```
{
    "multi_store_customers": 10, // Customers that visited more than one store
    "single_store_customers": 20 // Customers that only visited the store in the store asked
}
```

Only look through different stores, different schemes from the same store is OK

_Originally posted by @MystikHub in https://github.com/MystikHub/sweng-12/issues/6#issuecomment-800143754_

**Comment by MystikHub** [comment]
Xiaowei's got this route done, we're just waiting on @AvalonXD to finish setting up the `back-end` folder

**Comment by AvalonXD** [comment]
This is done, right? So we can close it?

**Comment by MystikHub** [comment]
Yeah, It's done
