### ISSUE TITLE
API Specification: /customer_growth

### ISSUE THREAD

**Issue by MystikHub** [MystikHub/sweng-12#9]
We should come up with some kind of expected output from making a request to /customer_growth on the back end, to help developing the back end route and the front end chart. Deciding on the format of the expected response early should help both teams get the feature done quickly.

This chart should show a growth chart displaying the amount of all time users, overall and by store

From the client specification:
The web app should scale correctly for stores with numerous locations and numerous
schemes. The dummy store I will be providing for you has 2 location and 2 loyalty
schemes. However I may later provide you with a different dummy store that has a
different amount of locations and schemes, and the code should work the same.

**Comment by AvalonXD** [comment]
![image](https://user-images.githubusercontent.com/60336995/112893926-2c42b300-90d3-11eb-98fe-ca8bb0fe2f31.png)
```
{
        "customer_growth_over_time": [10, 20, 30, 45, 60, 70, 100],
        "timescale_of_the_dates":  ["2020-10", "2020-11", "2020-12", "2021-01", "2021-02", "2021-03", "2021-04"]
}
```
In the full implementation, we'd also pull through multiple stores customer rates over time.
